# Generated by Django 5.1.2 on 2024-11-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='title',
        ),
    ]
