# Generated by Django 5.1.2 on 2024-11-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='pengguna',
        ),
    ]
